name: HeartBeat-Business
favicon: null
layout_spectrum: 0.7091080541722476
typography_spectrum: 0.3550597350113094
title: Führung und Veränderung in der digitalen Welt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#da243d'
    - '#ffffff'
    - '#58585a'
    - '#c1c1c1'
    - '#878787'
  brandStrength: 0.8685209322720766
  lightness: 0.4233906662557274
  saturation: 0.88166816951707
  rhythmicContrast: 0.5921608442440629
purpose: []
